### ISSUE TITLE
raises ValueError: incomplete format when logging starting debug message

### ISSUE THREAD

**Issue by alacham** [RedHatQE/wait_for#23]
example of failing arguments for logger.debug

`'Started %(message)r at %(time)' % {'message': 'function _wait_for_pcap_to_appear()', 'time': 205755.13175536}`

PR with fix: https://github.com/RedHatQE/wait_for/pull/22

**Comment by jaryn** [comment]
I belive this was fixed an can be closed.

**Comment by RonnyPfannschmidt** [comment]
@quarckster dito
